# https://travis-ci.org/spyder-ide/spyder-notebook

language: generic
dist: xenial
services:
    - xvfb

matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION=2.7 USE_CONDA=yes
    - env: PYTHON_VERSION=3.6 USE_CONDA=yes
    - env: PYTHON_VERSION=3.7 USE_CONDA=yes

before_install:
  # Avoid annoying focus problems when running tests
  # See discussion in e.g. https://github.com/spyder-ide/spyder/pull/6132
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager xterm libxkbcommon-x11-0
  - matchbox-window-manager&
  - sleep 5

install:
  - ./continuous_integration/circle/install.sh

script:
  - ./continuous_integration/circle/run_tests.sh

after_success:
  - ./continuous_integration/circle/coverage.sh
